Tweak wording in Markdown guide
dekkerglen/CubeCobra pull request #1594
Opened 2020-09-11 21:10 UTC by austin-schaefer

First PR on this project, so please let me know if I've run afoul of any guidelines! 

Made some minor wording tweaks to the new Markdown syntax guide to improve clarity and address a few minor typos.

2020-09-11 21:25 UTC, dekkerglen commented
Looks good, left one comment, also there are some minor conflicts from a hotfix I pushed out

2020-09-13 19:49 UTC, dekkerglen commented
I've merged and resolved conflicts to another branch and will merge in. Thank you!

2020-09-13 19:49 UTC, closed without merging

2020-09-13 19:49 UTC, dekkerglen requested changes

2020-09-14 17:47 UTC, austin-schaefer commented on src/pages/MarkdownPage.js
> +          to link to a specific version, you can supply a [Scryfall ID](https://scryfall.com/docs/api/cards/id).
Yeah that was the intent, thanks for catching this! Not too familiar with the markup here. I'm a docs person rather than an engineer.

2020-09-14 17:48 UTC, austin-schaefer commented
Thanks @dekkerglen ! I'm a docs writer rather than an engineer. While I can't help with code, I'm really happy to help improve documentation for Cube Cobra so feel free to hit me up there!