Added popularity sort
dekkerglen/CubeCobra pull request #1931
Opened 2021-05-28 15:57 UTC by Balkmeister

You can now sort by popularity (cube inclusion percentage)

2021-05-28 18:06 UTC, lunakv commented
Typographic note: the ranges should all be denoted by en dashes, not hyphens.

2021-05-30 23:32 UTC, ruler501 requested changes

2021-05-30 23:32 UTC, ruler501 commented on models/cardHistory.js
> +cardHistorySchema.index({ oracleId: 1 });
This is redundant, you can index on prefixes of other indices.

2021-05-30 23:32 UTC, ruler501 commented on serverjs/updatecards.js
> +  newcard.popularity = Math.round(catalog.poplularitydict[card.oracle_id] * 1000.0) / 10 || 0;
Why not store this as full precision?

2021-05-30 23:32 UTC, ruler501 commented on src/utils/Sort.js
> +    else if (popularity < 100) ret = ['50-100%'];
Just for completeness sake (and local testing) this should be `<=` for the highest bracket.

2021-06-09 14:50 UTC, merged