Fix +2 mace breaking filters
dekkerglen/CubeCobra pull request #2147
Opened 2021-07-17 18:09 UTC by dekkerglen

The problem: using filters when +2 mace is in the available pool causes the parser to crash.

The cause: when replacing the name in the oracle text with a placeholder, we treat the name as a regular expression, where `+` has special meaning

The solution: Treat any `+`'s in card names as string literals

2021-07-17 18:33 UTC, ruler501 requested changes
This should be a global replacement in the string for future proofing.

2021-07-17 19:20 UTC, dekkerglen commented
No, there are many places the name is used not as a regex

2021-07-18 12:12 UTC, ruler501 commented
You misunderstood. You should replace all instances of + not just the first.

2021-07-20 08:15 UTC, lunakv commented on src/filtering/FuncOperations.js
> +      .replace(new RegExp(card.details.name.replace('+', '\\+'), 'g'), NAME_PLACEHOLDER)
```suggestion
      .replace(new RegExp(card.details.name.replace(/+/g, '\\+'), 'g'), NAME_PLACEHOLDER)
```

2021-07-20 08:21 UTC, lunakv commented on src/filtering/FuncOperations.js
> +      .replace(new RegExp(card.details.name.replace('+', '\\+'), 'g'), NAME_PLACEHOLDER)
by the way, this all is the result of Node not having a proper `replaceAll` function until v15, which is just dumb.

2021-07-22 13:31 UTC, merged