Draft deck csv export [issue-2295]
dekkerglen/CubeCobra pull request #2356
Opened 2023-02-25 05:56 UTC by roborocket

CSV deck export is formatted to integrate seamlessly with TopDecked's importer. This allows the exact printing of card to be accurately reflected on deck import, with minimal user hassle.

Uses existing logic from other deck exports to count the quantity of cards in the deck, then writes csv file for quantity, name, scryfall ID, and zone (main or side). These are the only supported parameters that are required by TopDecked. TopDecked will coalesce multiple printings of the same card, so this PR does not account for that issue.

This feature can be expanded in a future pull request to export a csv matching the current cube-wide csv export function. 

Creates new button in dropdown list to initiate export on cube deck page.

2023-02-26 01:38 UTC, dekkerglen requested changes

2023-02-26 01:38 UTC, dekkerglen commented on routes/cube/deck.js
> +    const seat = deck.seats[0];
you have the `seat` parameter, but only download seat 0. For multiplayer drafts, this means that only player 1 would be able to download their decks

2023-02-26 01:38 UTC, dekkerglen commented on routes/cube/deck.js
> +    const DECK_CSV_HEADER = 'Quantity,"Name",Scryfall,Zone';
this should be declared outside of this scope

2023-02-26 01:38 UTC, dekkerglen commented on routes/cube/deck.js
> +          const details = carddb.cardFromId(card.cardID);
card details are already populated, you can just access card.details

2023-02-26 01:38 UTC, dekkerglen commented on routes/cube/deck.js
> +          const name = `${details.name}`;
I recommend using oracle_id over name, generally better practice

2023-02-26 01:38 UTC, dekkerglen commented on routes/cube/deck.js
> +          const name = `${details.name}`;
(there are some cards that share a name, but oracle id is unique for each game piece)

2023-03-02 04:26 UTC, roborocket commented on routes/cube/deck.js
> +const DECK_CSV_HEADER = 'Quantity,"Name",Scryfall,Zone';
Relocated

2023-03-02 04:27 UTC, roborocket commented on routes/cube/deck.js
> +    const seat = deck.seats[req.params.seat];
Reset params to match other export modes

2023-03-02 04:28 UTC, roborocket commented on routes/cube/deck.js
> +    const mainCardName = {};
Added definition to pull name of card due to changes to "oracle_id" instead of name below

2023-03-02 04:28 UTC, roborocket commented on routes/cube/deck.js
> +          const oracle_id = `${card.details.oracle_id}`;
Accessed card.details directly, and changed identifier to "oracle_id"

2024-07-09 22:58 UTC, merged