2427: add cards with special characters while specifying version
dekkerglen/CubeCobra pull request #2428
Opened 2023-12-27 01:48 UTC by adrianbw

2023-12-27 01:51 UTC, adrianbw commented on .gitignore
> +.DS_Store
Added for macOS development.

2023-12-27 01:54 UTC, adrianbw commented on serverjs/carddb.js
> +}
Extracted this to a helper so we can use it both places.

2023-12-27 01:54 UTC, adrianbw commented on serverjs/carddb.js
> +  return data.nameToId[normalizeName(name)];
Use the new helper function.

2023-12-27 01:54 UTC, adrianbw commented on serverjs/carddb.js
> +const getReasonableCardByOracle = (oracleId) => cardFromId(data.oracleToId[oracleId][0]);
Autofixed.

2023-12-27 01:54 UTC, adrianbw commented on serverjs/carddb.js
> +    ]),
Autofixed.

2023-12-27 10:00 UTC, lunakv requested changes
The changes look good. 👍 Just one thing, the input name should also be normalized.

With these changes, if someone wants to look for "Lórien Revealed", they can type "lorien revealed" and get a match, but if someone types the actual name because they have an "ó" symbol on their keyboard, it won't be found because you're comparing the raw (lowercased) input with a fully normalized card name.

2023-12-27 16:20 UTC, merged

2023-12-28 01:16 UTC, adrianbw commented
@lunakv I fixed that in https://github.com/dekkerglen/CubeCobra/pull/2431.